# Generated by Django 5.2.7 on 2026-04-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='records',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
