# Generated by Django 6.0.3 on 2026-04-05 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_user_records_created_by_alter_records_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('type', models.CharField(choices=[('INCOME', 'income'), ('EXPENSE', 'expense ')], max_length=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('RENT', 'Rent'), ('TRANSPORT', 'Transport'), ('UTILITIES', 'Utilities'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('SHOPPING', 'Shopping'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('SALARY', 'Salary'), ('FREELANCE', 'Freelance'), ('BUSINESS', 'Business'), ('INVESTMENT', 'Investment'), ('BONUS', 'Bonus'), ('OTHER_INCOME', 'Other Income')], max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Records',
        ),
    ]
