# Generated by Django 6.0.3 on 2026-04-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_delete_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
